services:
  gha-fix:
    image: marcellodesales/gha-sha-versioning
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
      args:
        GO_VERSION: ${GO_VERSION:-1.24.1}
        VERSION: ${VERSION:-dev}
        VCS_REF: ${VCS_REF:-unknown}
        BUILD_DATE: ${BUILD_DATE:-}
    environment:
      - GITHUB_TOKEN

    working_dir: /workspace
    volumes:
      - $PWD:/workspace
