name: Call gha-lint
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      # Manually trigger this workflow to pass required status check
      - ready_for_review
    paths:
      - '.github/**'
jobs:
  gha-sha-pinning:
    name: ðŸ“Œ gha-sha-pinning
    permissions:
      contents: write
      pull-requests: write
    uses: Finatext/workflows-public/.github/workflows/gha-lint.yml@main
    secrets: inherit
